name: Build the LaTeX template

on:
  push:
    branches:
      - main
  pull_request:

env:
  VERSION_FILE: NOVAthesisFiles/nt-version.sty

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.actor != 'my_bot_account'
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract version number from nt-version.sty
        run: |
          version=$(grep novathesisversion $VERSION_FILE | cut -d "{" -f3 | cut -d "}" -f1)
          echo "Version number is $version"
      - name: Compile the LaTeX template
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: bash .Build/build.sh
      - name: Upload the template PDF file
        uses: actions/upload-artifact@v4
        with:
          name: Template
          path: template.pdf
      - name: Push changes to the repository
        run: |
          version=$(grep novathesisversion $VERSION_FILE | cut -d "{" -f3 | cut -d "}" -f1)
          author_email=$(git log -1 --pretty=format:'%ae')
          author_name=$(git log -1 --pretty=format:'%an')
          git config --global user.email "$author_email"
          git config --global user.name "$author_name"
          git add -f template.pdf
          git commit -m "Upload PDF"
          git push
